########################################################################
# This file was auto-generated by the Terrafuck CLI                    #
# https://github.com/toptobes/terrform-brainfuck-interpreter           #
#                                                                      #
# (please send help I'm locked in his basement being forced to re-type #
# all of this by hand each time the CLI is called or he won't feed me) #
########################################################################

variable "code" {
  type        = string
  description = "The actual brainfuck code to interpret (e.g. \">+[+[<]>>+<+]>.\")"
}

variable "tape" {
  type        = list(number)
  description = "Brainfuck's memory tape (e.g. [0, 0, 0, 0, 0, 0, 0, 0, 0, 0])"
}

variable "input" {
  type        = string
  default     = ""
  description = "The input to pull from when the ',' command is used (e.g. \"Hi!\"). Must correspond to a byte between 0-255"
}

variable "tape_ptr" {
  type        = number
  default     = 0
  description = "The initial starting index in the memory tape"
}

variable "code_ptr" {
  type        = number
  default     = 0
  description = "The initial starting index in the brainfuck code"
}

variable "output" {
  type        = string
  default     = ""
  description = "The initial output string (not sure why you wouldn't just leave it blank but whatever)"
}

module "bracket_lut" {
  source = "./modules/bracket_lut"
  code   = var.code
}

module "interpreter" {
  source      = "./modules/interpreter"
  code        = var.code
  bracket_lut = module.bracket_lut.lut
  code_ptr    = var.code_ptr
  input       = var.input
  output      = var.output
  tape        = var.tape
  tape_ptr    = var.tape_ptr
}

output "output" {
  value       = module.interpreter.output
  description = "The output values from the brainfuck code (if you used the '.' command)"
}

output "tape" {
  value       = module.interpreter.tape
  description = "The resulting tape after the modifications made by the brainfuck code"
}

output "debug" {
  value = {
    final_input    = module.interpreter.final_iteration.input
    final_tape_ptr = module.interpreter.final_iteration.tape_ptr
    final_code_ptr = module.interpreter.final_iteration.code_ptr
    steps_taken    = module.interpreter.final_iteration.steps_taken
    bracket_lut    = module.bracket_lut.lut
  }
  description = "Various values that may be useful for debugging any terrafucked-up output"
}
